CREATE TABLE `LIVRO` (
	`Cod_livro` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`Titulo` VARCHAR(45) NOT NULL UNIQUE,
	`Nome_autor` VARCHAR(45) NOT NULL,
	`Nome_editora` VARCHAR(45) NOT NULL,
	PRIMARY KEY (`Cod_livro`)
);
ALTER TABLE `LIVRO` ADD CONSTRAINT `LIVRO_fk0` FOREIGN KEY (`Nome_editora`) REFERENCES `EDITORA`(`Nome`);
ALTER TABLE `LIVRO` ADD CONSTRAINT `LIVRO_fk1` FOREIGN KEY (`Nome_autor`) REFERENCES `LIVRO_AUTOR`(`Nome_autor`);


CREATE TABLE `LIVRO_AUTOR` (
	`Cod_autor` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`Nome_autor` VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY (`Nome_autor`)
);

CREATE TABLE `EDITORA` (
	`Cod_editora` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`Nome` VARCHAR(50) NOT NULL UNIQUE,
	`Endereco` VARCHAR(100) NOT NULL,
	`Telefone` VARCHAR(15) NOT NULL,
	PRIMARY KEY (`Nome`)
);

CREATE TABLE `LIVRO_COPIAS` (
	`Cod_livro` INT NOT NULL,
	`Cod_unidade` INT NOT NULL,
	`Qt_copia` INT NOT NULL,
	PRIMARY KEY (`Cod_livro`,`Cod_unidade`)
);
ALTER TABLE `LIVRO_COPIAS` ADD CONSTRAINT `LIVRO_COPIAS_fk0` FOREIGN KEY (`Cod_livro`) REFERENCES `LIVRO`(`Cod_livro`);
ALTER TABLE `LIVRO_COPIAS` ADD CONSTRAINT `LIVRO_COPIAS_fk1` FOREIGN KEY (`Cod_unidade`) REFERENCES `UNIDADE_BIBLIOTECA`(`Cod_unidade`);


CREATE TABLE `LIVRO_EMPRESTIMO` (
	`Cod_livro` INT NOT NULL,
	`Cod_unidade` INT NOT NULL,
	`Nr_cartao` INT NOT NULL,
	`Data_emprestimo` varchar(10) NOT NULL,
	`Data_devolucao` varchar(10) NOT NULL,
	PRIMARY KEY (`Cod_livro`,`Cod_unidade`,`Nr_cartao`)
);
ALTER TABLE `LIVRO_EMPRESTIMO` ADD CONSTRAINT `LIVRO_EMPRESTIMO_fk0` FOREIGN KEY (`Cod_livro`) REFERENCES `LIVRO`(`Cod_livro`);
ALTER TABLE `LIVRO_EMPRESTIMO` ADD CONSTRAINT `LIVRO_EMPRESTIMO_fk1` FOREIGN KEY (`Cod_unidade`) REFERENCES `UNIDADE_BIBLIOTECA`(`Cod_unidade`);
ALTER TABLE `LIVRO_EMPRESTIMO` ADD CONSTRAINT `LIVRO_EMPRESTIMO_fk2` FOREIGN KEY (`Nr_cartao`) REFERENCES `USUARIO`(`Num_cartao`);

CREATE TABLE `UNIDADE_BIBLIOTECA` (
	`Cod_unidade` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`Nome_unidade` VARCHAR(45) NOT NULL,
	`Endereco` VARCHAR(100) NOT NULL,
	PRIMARY KEY (`Nome_unidade`)
);

CREATE TABLE `USUARIO` (
	`Num_cartao` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`Nome` VARCHAR(45) NOT NULL UNIQUE,
	`Endereco` VARCHAR(100) NOT NULL,
	`Telefone` VARCHAR(10) NOT NULL UNIQUE,
	PRIMARY KEY (`Nome`)
);















